# Generated by Django 3.1.3 on 2020-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20201219_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
